### ISSUE TITLE
Tracking issue for crate evaluation

### ISSUE THREAD

**Issue by sfackler** [danburkert/memmap-rs#38]
- [ ] [Expand crate-level documentation](https://github.com/danburkert/memmap-rs/issues/32)
- [ ] [Add examples to methods](https://github.com/danburkert/memmap-rs/issues/34)
- [ ] [Overhaul API](https://github.com/danburkert/memmap-rs/issues/33)
- [ ] [Add CI Badges to Cargo.toml](https://github.com/danburkert/memmap-rs/issues/35)
- [ ] [Add `#[doc(html_root_url = "...")]` annotation to crate root](https://github.com/danburkert/memmap-rs/issues/36)
- [ ] [Document error conditions for fallible methods in a separate "Errors" section](https://github.com/danburkert/memmap-rs/issues/37)

**Comment by brson** [comment]
@danburkert "Add examples" can be checked.

**Comment by KodrAus** [comment]
Based on #46 and #31 it looks like we could use someone with familiarity, or at least ready access to, Windows to help get `memmap` over the line.

@danburkert would it be helpful if someone pulled the PR in #46 and spent some time poking it on Windows to fix the test failure?

**Comment by bjnyfv** [comment]
@KodrAus @danburkert I can help poke around in PR #46. I got my windows environment setup last night and was able to reproduce the failure. I am still fairly new to Rust and haven’t done much windows-specific development, but if you would like an extra set of eyes I am more than happy to help.

**Comment by KodrAus** [comment]
Thanks @bjnyfv! I'm not 100% sure whether @danburkert has more they want to do with that PR, but if you're able to produce a fix that gets the build green then opening up a new PR and noting that it's based on #46 would probably be helpful.

Thanks again!

**Comment by KodrAus** [comment]
@bjnyfv if you'd like a sounding board anytime for any blitz work, please join on the [Gitter channel](https://gitter.im/rust-impl-period/WG-libz-blitz). I haven't done much Windows native dev either, but will try help where I can.

**Comment by bjnyfv** [comment]
Thank you for the heads-up @KodrAus! I checked out the Gitter channel as suggested and noticed that @toankitsingh also mentioned helping out with the Windows issues. Perhaps @toankitsing and I can touch base if he is reading this. (I will also post a message in Gitter for him to hopefully see).

**Comment by KodrAus** [comment]
Now that `memmap` is stable we should be able to close this.
